version: '3'

services:
  nginx-relay:
    build: ./nginx-relay/
    restart: unless-stopped
    volumes:
      - ./data/nginx-relay:/etc/nginx/conf.d
    # This config assumes that the traefik container has access to the bridge network
    network_mode: bridge
    ports: 
      - 4433
    labels:
      - traefik.tcp.routers.signal-proxy.rule=HostSNI("signal.mydomain.com") 
      - traefik.tcp.routers.signal-proxy.tls=true
      - traefik.tcp.routers.signal-proxy.tls.certresolver=leresolver
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; /opt/nginx/sbin/nginx -s reload; done & /opt/nginx/sbin/nginx -c /etc/nginx/conf.d/nginx.conf -g \"daemon off;\"'"

